### ISSUE TITLE
Only deploy submenu for the active menu/page

### ISSUE THREAD

**Issue by quesnel** [thingsym/hugo-theme-techdoc#1]
First, thank for your theme. I am trying it on my website (https://www.vle-project.org).

To reduce the size of the left menu, it is possible to only open menu and hierarchized sub-menu for the active page ?

**Comment by galexrt** [comment]
@quesnel I have implemented something like this in my fork https://github.com/galexrt/hugo-theme-techdoc/commit/a3db3d09bfc897eaf834f3e402e489f4c2cc980a
The template code could probably be made cleaner.

**Comment by thingsym** [comment]
Hi, @quesnel.
Thank you for your suggestion.

This was implemented in version 0.4.0.
You can select Menu style `Open Menu` or `Slide Menu`.

Menu style screenshots are on the following page.
https://themes.gohugo.io//theme/hugo-theme-techdoc/getting-started/screenshot/#menu-style
