### ISSUE TITLE
UniqueID throwing a warning when building

### ISSUE THREAD

**Issue by rbucker** [thingsym/hugo-theme-techdoc#10]
Building sites … WARN 2019/11/30 07:36:32 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

Pretty sure it's in the menu where "file" is probably CurrentNode

**Comment by thingsym** [comment]
Hi!
Thank you for your report.

This was fixed in version 0.6.0.
