### ISSUE TITLE
Wrong image path inside the cover image?

### ISSUE THREAD

**Issue by garethjax** [thingsym/hugo-theme-techdoc#11]
The "home page" example content seems to have a "home image" reference inside the front-matter, but the image is not found inside the folder files nor is it appearing while testing it.

How should it work?

Thanks for the great effort!

**Comment by thingsym** [comment]
Hi @garethjax.
Thank you for your report.

That's fixed.
Open graph images should be stored in `static/images`.

For the front-matter setting, see below:
https://github.com/thingsym/hugo-theme-techdoc/blob/master/exampleSite/content/_index.md
