### ISSUE TITLE
Order of Side Menu Items

### ISSUE THREAD

**Issue by jcrubino** [thingsym/hugo-theme-techdoc#13]
How is the order of the side menu determined?

**Comment by thingsym** [comment]
Hi, @jcrubino.

The order of the side menu is determined by the `weight` of Front Matter.
Lower weight gets higher precedence. So menu with lower weight will come first.

https://gohugo.io/content-management/front-matter/

The sample of Front Matter with weight is as below.

https://raw.githubusercontent.com/thingsym/hugo-theme-techdoc/master/exampleSite/content/chapter2/2.md

**Comment by jcrubino** [comment]
Yes.  I did find the answers in the Hugo docs eventually.
Closing.
