### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by adelerhof** [thingsym/hugo-theme-techdoc#18]
Where do I place my favicon.ico?
I placed it in static/img/favicon.ico and static/imgages/favicon.ico, it doesn't use it.
I can't find it in the code as well (I'm not a html coder, so I might be wrong)

Thanks in advance

**Comment by thingsym** [comment]
Hi @adelerhof.

A simple way is to place favicon.ico in `static`.

If you want to specify a directory and place it, or use a png image as favicon, add a tag using custom-head.html.

**Comment by adelerhof** [comment]
This works,thanks!
