### ISSUE TITLE
Panel Shortcode: Markdown isn't processed

### ISSUE THREAD

**Issue by ckamps** [thingsym/hugo-theme-techdoc#19]
Is there a way to get markdown processed for the inline portion of the panel shortcode?

For example, when I include a simple link:
```
{{< panel status="notice" title="My Title" >}}
[I'm an inline-style link with title](https://www.google.com "Google's Homepage")
{{< /panel >}}
```
The link is not rendered:

![Screen Shot 2020-03-24 at 2 01 59 PM](https://user-images.githubusercontent.com/1332810/77466303-13286780-6dd8-11ea-8ac9-83e9a559320b.png)

It appears that no markdown is processed.

**Comment by thingsym** [comment]
Hi @ckamps.

The `<` character does not render markdown.

https://gohugo.io/content-management/shortcodes/#shortcodes-without-markdown

If you render markdown, you should use the `%` character.

```
{{% panel status="notice" title="My Title" %}}
[I'm an inline-style link with title](https://www.google.com "Google's Homepage")
{{% /panel %}}
```
