### ISSUE TITLE
Side Menu Levels

### ISSUE THREAD

**Issue by mrxrsd** [thingsym/hugo-theme-techdoc#25]
Is it possible to add unlimited levels?

Thanks.

**Comment by thingsym** [comment]
Hi @mrxrsd,
Thank you for your issue.

The document hierarchy is unlimite.
It also means that the menu levels is unlimited levels.

The Side Menu Levels has up to 2 levels of indentation.
In the next release, I will increase to 5 levels to Side Menu Levels.

**Comment by thingsym** [comment]
It's fixed.
In version 0.9.2, The Side Menu Levels has up to 5 levels of indentation.

Sample pages has been added to the Demo site:
https://themes.gohugo.io//theme/hugo-theme-techdoc/chapter4/
