### ISSUE TITLE
Appends "s" to Menu

### ISSUE THREAD

**Issue by theAusMenace** [thingsym/hugo-theme-techdoc#30]
Hi Team

Please excuse if I'm doing something wrong, however ...

$ hugo new "TEST/test.md"
Menu gets an "s" appended so TEST becomes TESTs

![image](https://user-images.githubusercontent.com/28998815/96325125-05d31300-1071-11eb-9baf-a7b6d40c4d53.png)

**Comment by thingsym** [comment]
Hi, @theAusMenace,

By default, Hugo pluralize titles in the list.

https://gohugo.io/getting-started/configuration/

If you change the setting as follows, it becomes singular.

```
pluralizeListTitles = false
```

**Comment by theAusMenace** [comment]
Thank you, apologies for the extended AFK.
