### ISSUE TITLE
Links in notice alerts barely readable

### ISSUE THREAD

**Issue by kiu** [thingsym/hugo-theme-techdoc#31]
Links inside notice alerts (especially hovers) are barely readable with the default CSS being used.

`{{< panel status="notice" title="Example Link in Alert" icon="fas fa-exclamation-triangle" >}}This is an example <a href="https://www.example.com">Link</a> inside a notice alert.{{< /panel >}}`

![image](https://user-images.githubusercontent.com/785968/97115082-d9646a00-16f4-11eb-8dbe-0efad9719fe6.png)

![image](https://user-images.githubusercontent.com/785968/97115091-ee40fd80-16f4-11eb-9f2c-ddc260d96255.png)

**Comment by thingsym** [comment]
Hi @kiu, 
Thank you for your issue.

In version 0.9.5, It's fixed.

Sample page:
https://themes.gohugo.io//theme/hugo-theme-techdoc/sample/custom-shortcodes/#alert-panel-with-titles-and-colors
