### ISSUE TITLE
"Last updated on " doesn't work properly

### ISSUE THREAD

**Issue by j3an-baptiste** [thingsym/hugo-theme-techdoc#5]
The "Last updated on" date is not working in the footer of the web pages.
The file last-updated.html from layouts/partials/ is:
Last updated on {{ $.Lastmod.Format ( $.Site.Params.lastUpdate | default "2 Jan 2006") }}
From this, I get "Last updated on 1 Jan 0001 " on all pages.

**Comment by thingsym** [comment]
Hi!
Thank you for issue.

Updated to version 0.2.2, fixed Lastmod's and PublishDate's initial value of 0001-01-01.

For your reference:
https://discourse.gohugo.io/t/how-to-use-the-publishdate-if-both-publishdate-and-date-are-set-in-frontmatter/5142/4
