### ISSUE TITLE
how to limit page width?

### ISSUE THREAD

**Issue by berndpfrommer** [thingsym/hugo-theme-techdoc#6]
I really like the theme, and I am using it to document a software project 
https://berndpfrommer.github.io/tagslam_web/

One question: Is there a way to limit the width of the page? The formatting looks a bit weird at times when the page is viewed on a wide screen (1920x1200). In particular the size of embedded videos then is really large, and I wasn't able to control their size. It would look neater if both videos and text were e.g. at most 800px wide.

**Comment by thingsym** [comment]
Hi, @berndpfrommer.
Thank you for using the theme.

You can add css to limit the page width.

As follows:
e.g. at most 800px wide

```
.container {
    max-width: 800px;
}
```

**Comment by berndpfrommer** [comment]
Thanks for the quick reply, but I'm not sure where to put it. I couldn't find a hook for custom css, so I hacked it directly into the theme file "static/css/theme.css", but it did not affect the rendering. Could you please advise?

**Comment by thingsym** [comment]
You can overwrite using custom-head.html

Base Template Lookup Order
https://gohugo.io/templates/base/#base-template-lookup-order

1. copy /themes/&lt;THEME&gt;/layouts/partials/custom-head.html in theme layouts directory to layouts/partials/custom-head.html

    The lookup order for custom-head.html is as follows:
    1. layouts/partials/custom-head.html
    2. /themes/&lt;THEME&gt;/layouts/partials/custom-head.html

2. put custom css in layouts/partials/custom-head.html

```
<style>
.container {
    max-width: 800px;
}
</style>
```

3. build website

**Comment by berndpfrommer** [comment]
Great, that worked!
Thanks so much!
