### ISSUE TITLE
table of contents for one of the pages in contents

### ISSUE THREAD

**Issue by langley** [thingsym/hugo-theme-techdoc#7]
The techdoc theme is GREAT, Thank You for creating it. 

One of the things I'd like to support in my pages is a table of contents for the material in the page. 
Is there a simple way to integrate this with the out of the box version of techdoc, or does supporting this mean that I need to create some new _index.html / _index.md files, a new partial or something like that? 

Thanks!

**Comment by thingsym** [comment]
Hi, @langley.
Thank you for your suggestion.

In version 0.5.0, I implemented the table of contents for the page to Techdoc theme.

Here is a sample page:
https://themes.gohugo.io/theme/hugo-theme-techdoc/sample/table-of-contents/

You can add a table of contents to the page.
To display the table of contents on the page, you add settings to the front matter of the .md file.

The `TableOfContents` field set to `true` in your content’s front matter will render a table of contents.

The setting example is as follows:

```
TableOfContents: true
```

https://raw.githubusercontent.com/thingsym/hugo-theme-techdoc/master/exampleSite/content/sample/table-of-contents.md
