### ISSUE TITLE
search feature

### ISSUE THREAD

**Issue by bzuelly** [thingsym/hugo-theme-techdoc#8]
Would it be possible to add a search box?

While unable to code it myself, i could assist with testing.

Thanks!

**Comment by thingsym** [comment]
Hi, @bzuelly.

Thank you for your issue.

In version 0.9.0, Hugo Theme Techdoc support search feature powered by Algolia. 

You can create a search page just by adding search shortcode.

Sample page is url below:
https://themes.gohugo.io//theme/hugo-theme-techdoc/sample/search-shortcode/
