### ISSUE TITLE
theme color

### ISSUE THREAD

**Issue by Amber1990Zhang** [thingsym/hugo-theme-techdoc#9]
How to set a customized theme color?

**Comment by thingsym** [comment]
Hi, @Amber1990Zhang.

You can set the theme color in config.toml.

You can set the `custom_font_color` and `custom_background_color` by the CSS color property on Theme settings section.

For your reference.
* https://themes.gohugo.io//theme/hugo-theme-techdoc/getting-started/configuration/
* https://developer.mozilla.org/en-US/docs/Web/CSS/color

**Comment by darielvicedo** [comment]
custom_background_color doesn't work, not in RGB nor hex.
